sites/models.py
from db import db, schema
from harperdb.exceptions import HarperDBError

table = "websites"


class Website:
    @staticmethod
    def create(url: str, username: str):
        payload = dict(username=username, url=url)
        return db.insert(schema, table, [payload])

    @staticmethod
    def get_all_websites(username: str):
        try:
            websites = db.search_by_value(schema, table, "username", username)
        except HarperDBError:
            websites = None
        return websites

    @staticmethod
    def get_website(website: str):
        try:
            site = db.search_by_value(schema, table, "url", website)
        except HarperDBError:
            site = None
        if site == []:
            site = None
        return site

sites/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class WebsiteForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])

sites/routes.py
from datetime import datetime, timedelta
from urllib.parse import urlparse

from api.utils import (
    get_data_for_a_period,
    get_referrer_country_pagevisit_browser_device,
)
from db import db
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from flask.helpers import flash
from flask_login import current_user, login_required
from pychartjs import BaseChart, ChartType, Color, Options

from .forms import WebsiteForm
from .models import Website
from .utils import country_codes

sites = Blueprint("sites", __name__, url_prefix="/sites")


@sites.route("/", methods=["GET", "POST"])
@login_required
def new_site():
    form = WebsiteForm()
    username = current_user.id
    if request.method == "POST" and form.validate_on_submit():
        website = form.name.data
        website_exists = Website.get_website(website)
        if website_exists is not None:
            flash("Website already added to amalytics")
            return redirect(url_for("sites.new_site"))
        if website[-1] == "/":
            website = website[:-1]
        website = urlparse(website).netloc
        if website == "":
            flash("Please enter a valid website")
            return redirect(url_for("sites.new_site"))
        Website.create(website, username)
    websites = Website.get_all_websites(username)
    return render_template("sites/new_site.html", form=form, websites=websites)


@sites.route("/<path:website>", methods=["GET", "POST"])
@login_required
def site(website: str):
    ts = (datetime.now() + timedelta(days=-30)).timestamp()
    data = db.sql(
        f"SELECT * FROM amalytics.clicks WHERE __createdtime__ > {ts} AND domain='{website}'"
    )
    if data is None:
        return jsonify(None)

    click_count = get_data_for_a_period(data)

    (
        referrer,
        countries,
        visits,
        browser_count,
        device_count,
    ) = get_referrer_country_pagevisit_browser_device(data)

    try:
        del referrer[""]
    except KeyError:
        pass

    result = dict()

    # Build chart for referrer count
    class ReferrerChart(BaseChart):
        type = ChartType.HorizontalBar

        class data:
            label = "Referrers"
            data = list(referrer.values())
            backgroundColor = Color.Palette(Color.Magenta, n=len(data), generator="hue")

        class labels:
            grouped = list(referrer.keys())

        class options:
            scales = {
                "xAxes": [
                    {
                        "ticks": {
                            "beginAtZero": True,
                        }
                    }
                ]
            }

    # Build chart for click count
    class ClickChart(BaseChart):
        type = ChartType.Line

        class data:
            label = "Views"
            data = list(click_count[30].values())
            backgroundColor = Color.Teal
            pointRadius = 4
            pointBackgroundColor = Color.Cyan

        class labels:
            grouped = list(click_count[30].keys())

        class options:
            scales = {
                "yAxes": [
                    {
                        "ticks": {
                            "beginAtZero": True,
                        }
                    }
                ]
            }

    # Build chart for the browser used
    class BrowserChart(BaseChart):
        type = ChartType.Pie

        class data:
            label = "Browser type used"
            data = list(browser_count.values())
            backgroundColor = Color.Palette(Color.Green, n=len(data), generator="hue")

        class labels:
            grouped = list(browser_count.keys())

    # Build chart for the device used
    class DeviceChart(BaseChart):
        type = ChartType.Pie

        class data:
            label = "Device type used"
            data = list(device_count.values())
            backgroundColor = Color.Palette(Color.Blue, n=len(data), generator="hue")

        class labels:
            grouped = list(device_count.keys())

    # Build chart for page visited
    class PageChart(BaseChart):
        type = ChartType.HorizontalBar

        class data:
            label = "Page visited"
            data = list(visits.values())
            backgroundColor = Color.Palette(Color.Cyan, n=len(data), generator="hue")

        class labels:
            grouped = list(visits.keys())

        class options:
            scales = {
                "xAxes": [
                    {
                        "ticks": {
                            "beginAtZero": True,
                        }
                    }
                ]
            }

    # Build chart for page visited
    class CountryChart(BaseChart):
        type = ChartType.HorizontalBar

        class data:
            label = "Views"
            data = list(countries.values())
            backgroundColor = Color.Palette(Color.Apricot, n=len(data), generator="hue")

        class labels:
            grouped = [country_codes.get(i) for i in countries.keys()]

        class options:
            scales = {
                "xAxes": [
                    {
                        "ticks": {
                            "beginAtZero": True,
                        }
                    }
                ]
            }

    total_clicks = dict()

    for i, v in click_count.items():
        total_clicks[i] = sum(v.values())

    result.update(total_clicks=total_clicks)

    return render_template(
        "sites/site.html",
        website=website,
        data=result,
        browserDataChart=BrowserChart().get(),
        deviceDataChart=DeviceChart().get(),
        clickChart=ClickChart().get(),
        referrerChart=ReferrerChart().get(),
        pageChart=PageChart().get(),
        countryChart=CountryChart().get(),
    )

templates/sites/new_site.html
{% extends 'base.html' %}

{% block title %}
{{current_user.id}} | Sites
{% endblock title %}

{% block content %}
<div class="text-white min-h-screen bg-base-200">
    <div class="container text-center mx-auto py-6 px-8">
        <h1 class="mb-5 text-5xl font-bold">
            Add New Website
        </h1>
        <form action="" method="post">
            {{form.csrf_token}}
            <div class="form-control">
                <label class="label">
                    <span class="label-text">Website</span>
                </label>
                <input name="name" required type="url" placeholder="Enter website URL" class="input input-bordered">
            </div> <br><br>
            <input type="submit" value="Add Website" class="btn btn-success">
        </form> <br><br>
        <p class="mb-5 text-2xl">
            After adding a new website for tracking, insert the following script just before the close of
            <code>body</code> tag. <br><br>
            <kbd>
                <div class="form-control">
                    <input type="text" class="input" id="foo"
                        value="<script src='https://amalytics.amalshaji.com/amalytics.js'></script>" readonly>
                    <!-- Trigger -->
                    <button class="btn"
                        data-clipboard-text="<script src='https://amalytics.amalshaji.com/amalytics.js'></script>">
                        Copy to clipboard
                    </button>
                </div>
            </kbd>
        </p>
        <script>
            new ClipboardJS(".btn");
        </script>
        <div class="divider"></div>
        <h1 class="mb-5 text-5xl font-bold">
            My Websites
        </h1> <br><br>
        <div class="mb-5 text-center mx-auto h-full px-auto">
            {% if websites is defined %}
            {% for website in websites %}

            <a href="{{url_for('sites.site', website=website.url)}}" class="btn btn-primary">{{website.url}}</a> <br>
            <br>

            {% endfor %}
            {% else %}
            No websites yet
            {% endif %}
        </div>
    </div>

</div>
{% endblock content %}

templates/sites/site.html
{% extends 'base.html' %}

{% block title %}
{{website}}
{% endblock title %}

{% block content %}

<div class="text-center items-center text-white min-h-screen bg-base-200">
    <h1 class="mb-5 pt-10 text-3xl font-bold">
        Analytics for {{website}} (last 30 days)
    </h1>
    <br><br>
    <div class="stats shadow border border-base-300">
        <div class="stat">
            <div id="30days" class="stat-title">Total Page Views in the last 30 days</div>
            <div class="stat-value">{{data.total_clicks.30}}</div>
        </div>
    </div>

    <div class="stats shadow">
        <div class="stat">
            <div id="7days" class="stat-title">Total Page Views in the last 7 days</div>
            <div class="stat-value">{{data.total_clicks.7}}</div>
        </div>
    </div>

    <div class="stats shadow">
        <div class="stat">
            <div id="1day" class="stat-title">Total Page Views today</div>
            <div class="stat-value">{{data.total_clicks.1}}</div>
        </div>
    </div>
    <br><br>

    <div class="card w-auto px-2 mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        View data
        <canvas id="clickData"></canvas>
        <br>
    </div>
    <br> <br>
    <div class="card w-auto mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        Device share
        <canvas id="deviceData"></canvas>
        <br>
    </div>
    <br> <br>
    <div class="card w-auto mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        Browser share
        <canvas id="browserData"></canvas>
        <br>
    </div>
    <br> <br>
    <div class="card w-auto px-2 mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        Referrer count
        <canvas id="referrerData"></canvas>
        <br>
    </div>
    <br> <br>
    <div class="card w-auto px-2 mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        Pages visited
        <canvas id="pageData"></canvas>
        <br>
    </div>
    <br> <br>
    <div class="card w-auto px-2 mx-2 lg:w-1/3 bg-base-100 md:absolute md:left-1/2 md:transform md:-translate-x-1/2">
        <br>
        Country of origin
        <canvas id="countryData"></canvas>
        <br>
    </div>
    <br> <br>
</div>

<script>
    var browserData = {{ browserDataChart | safe }}
    var ctx = document.getElementById("browserData").getContext('2d');
    var myChart = new Chart(ctx, browserData);

    var deviceData = {{ deviceDataChart | safe }}
    var ctx = document.getElementById("deviceData").getContext('2d');
    var myChart = new Chart(ctx, deviceData);

    var clickData = {{ clickChart | safe }}
    var ctx = document.getElementById("clickData").getContext('2d');
    var myChart = new Chart(ctx, clickData);

    var referrerData = {{ referrerChart | safe }}
    var ctx = document.getElementById("referrerData").getContext('2d');
    var myChart = new Chart(ctx, referrerData);

    var pageData = {{ pageChart | safe }}
    var ctx = document.getElementById("pageData").getContext('2d');
    var myChart = new Chart(ctx, pageData);

    var countryData = {{ countryChart | safe }}
    var ctx = document.getElementById("countryData").getContext('2d');
    var myChart = new Chart(ctx, countryData);
</script>


{% endblock content %}